version: '3.7'

services:

  php-seller-api:
    build:
      context: ./
      target: development
    volumes:
      - ./seller:/var/www/html
    environment:
       XDEBUG_MODE: coverage
    depends_on:
      - mysql-anwalt
    command: >
      sh -c "composer install && composer dump-autoload && apachectl -D FOREGROUND"

  php-contact-api:
    build:
      context: ./
      target: development
    volumes:
      - ./contact:/var/www/html
    environment:
      XDEBUG_MODE: coverage
    depends_on:
      - mysql-anwalt
    command: >
      sh -c "composer install && composer dump-autoload && apachectl -D FOREGROUND"

  php-sale-api:
    build:
      context: ./
      target: development
    volumes:
      - ./sale:/var/www/html
    environment:
      XDEBUG_MODE: coverage
    depends_on:
      - mysql-anwalt
    command: >
      sh -c "composer install && composer dump-autoload && apachectl -D FOREGROUND"

  php-csv-parser-api:
    build:
      context: ./
      target: development
    volumes:
      - ./csv-parser:/var/www/html
    environment:
      XDEBUG_MODE: coverage
    depends_on:
      - mysql-anwalt
    command: >
      sh -c "composer install && composer dump-autoload && apachectl -D FOREGROUND"

  php-csv-parser-worker:
    build:
      context: ./
      target: development
      dockerfile: Dockerfile.parser.worker
    volumes:
      - ./csv-parser:/var/www/html
    restart: on-failure
    depends_on:
      - mysql-anwalt
    command: >
      sh -c "composer install && composer dump-autoload && cd vendor/bin && ./laminas parser:parse"

  nginx-anwalt:
    image: nginx:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:8080"
    depends_on:
      - php-seller-api
      - php-sale-api
      - php-contact-api
      - php-csv-parser-api

  mysql-anwalt:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: GCECjdRLf7RvwJLJ
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - anwalt-data:/var/lib/mysql

  phpmyadmin-anwalt:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: mysql-anwalt
      PMA_PASSWORD: GCECjdRLf7RvwJLJ
      PMA_USER: root
    ports:
      - "81:80"
    depends_on:
      - mysql-anwalt

volumes:
  anwalt-data: